- name: check anyenv exists
  stat:
    path: /opt/anyenv
  register: anyenv_dir
- name: setup anyenvs
  when: not anyenv_dir.stat.exists
  block:
    - name: ensure ruby-build dependencies
      become: true
      apt:
        pkg:
          - autoconf
          - bison
          - build-essential
          - libssl-dev
          - libyaml-dev
          - libreadline6-dev
          - zlib1g-dev
          - libncurses5-dev
          - libffi-dev
          - libgdbm6
          - libgdbm-dev
    - name: mkdir anyenv
      become: true
      file:
        path: /opt/anyenv
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: install anyenv
      git:
        repo: https://github.com/anyenv/anyenv.git
        dest: /opt/anyenv
        accept_hostkey: yes
    - name: symlink anyenv
      become: true
      file:
        src: /opt/anyenv/bin/anyenv
        dest: /usr/local/bin/anyenv
        state: link
    - name: run anyenv install
      shell: |
        export ANYENV_ROOT=/opt/anyenv
        export ANYENV_DEFINITION_ROOT=/opt/anyenv/anyenv-install-config
        anyenv install --force-init
        anyenv install rbenv
        anyenv install nodenv
    - name: symlink envs
      become: true
      file:
        src: "/opt/anyenv/envs/{{ item }}/bin/{{ item }}"
        dest: /usr/local/bin/{{ item }}
        state: link
      loop:
        # rbenvはsymlinkでは動かなくなったので、ここではlinkしない
        # refs shell_commands/rbenv
        #- rbenv
        - nodenv

- name: check anyenv-update exists
  stat:
    path: /opt/anyenv/plugins/anyenv-update
  register: anyenv_update_dir
- name: setup anyenv-update
  when: not anyenv_update_dir.stat.exists
  block:
    - name: mkdir anyenv/plugins
      become: true
      file:
        path: /opt/anyenv/plugins
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: install anyenv-update
      git:
        repo: https://github.com/znz/anyenv-update.git
        dest: /opt/anyenv/plugins/anyenv-update
        accept_hostkey: yes

