- name: check anyenv exists
  stat:
    path: /opt/anyenv
  register: anyenv_dir
- name: setup anyenvs
  when: not anyenv_dir.stat.exists
  block:
    - name: ensure ruby-build dependencies
      become: true
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - autoconf
        - bison
        - build-essential
        - libssl-dev
        - libyaml-dev
        - libreadline6-dev
        - zlib1g-dev
        - libncurses5-dev
        - libffi-dev
        - libgdbm6
        - libgdbm-dev
    - name: mkdir rbenv
      become: true
      file:
        path: /opt/anyenv
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - name: install anyenv
      git:
        repo: https://github.com/anyenv/anyenv.git
        dest: /opt/anyenv
        accept_hostkey: yes
    - name: symlink anyenv
      file:
        src: /opt/anyenv/bin/anyenv
        dest: /opt/bin/anyenv
        state: link
    - name: run anyenv install
      shell: |
        export ANYENV_ROOT=/opt/anyenv
        export ANYENV_DEFINITION_ROOT=/opt/anyenv/anyenv-install-config
        /opt/bin/anyenv install --force-init
        /opt/bin/anyenv install rbenv
        /opt/bin/anyenv install nodenv
    - name: symlink envs
      file:
        src: "/opt/anyenv/envs/{{ item }}/bin/{{ item }}"
        dest: /opt/bin/{{ item }}
        state: link
      loop:
        - rbenv
        - nodenv
