- name: ensure ruby-build dependencies
  become: true
  apt:
    pkg:
      - autoconf
      - bison
      - build-essential
      - libssl-dev
      - libyaml-dev
      - libreadline6-dev
      - zlib1g-dev
      - libncurses5-dev
      - libffi-dev
      - libgdbm6
      - libgdbm-dev

- name: ensure asdf directory
  become: true
  file:
    # 本来ASDF_DIRで指定していればどんなパスでも良いと思うが、vscodeのruby-lsp拡張の実装がASDF_DIRなどは読まず
    # いくつかのパスを決め打ちで捜索するようになっているため、それに合わせたパスにしている。
    # refs https://github.com/Shopify/ruby-lsp/blob/0d310e19b85ae6f554df3824f4b8439176952dae/vscode/src/ruby/asdf.ts#L53-L73
    path: /opt/asdf-vm
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

# FIXME: いい感じにchangedにならないようにできるか

- name: ensure asdf plugins
  shell: |
    export ASDF_DIR=/opt/asdf-vm
    export ASDF_DATA_DIR=$ASDF_DIR
    export PATH=$ASDF_DIR/bin/:$PATH
    asdf plugin add nodejs https://github.com/asdf-vm/asdf-nodejs.git
    asdf plugin add ruby https://github.com/asdf-vm/asdf-ruby.git
    asdf plugin add golang https://github.com/asdf-community/asdf-golang.git
    asdf plugin add terraform https://github.com/asdf-community/asdf-hashicorp.git
    asdf plugin add deno https://github.com/asdf-community/asdf-deno.git

- name: ensure latest asdf installs
  shell: |
    export ASDF_DIR=/opt/asdf-vm
    export ASDF_DATA_DIR=$ASDF_DIR
    export PATH=$ASDF_DIR/bin/:$PATH

    asdf plugin update --all > /dev/null

    node=$(asdf cmd nodejs resolve lts)
    asdf install nodejs $node
    asdf set --home nodejs $node

    for c in "ruby" "golang" "terraform" "deno"; do
      # 数字だけに絞ることでjrubyなどの別種やrc版などを取り除く
      version=$(asdf list all $c | grep "^[0-9\.]\+\$" | tail -n 1)
      asdf install $c $version
      asdf set --home $c $version
    done
