- name: install awscli
  become: true
  command: pip install --upgrade awscli
- name: install session manager plugin
  become: true
  apt:
    deb: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb
