# refs https://docs.docker.com/engine/install/ubuntu/
- name: install depencencies
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: app repository
  become: true
  block:
    - apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/trusted.gpg.d/docker.gpg
        state: present
    - apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu focal stable"
        state: present

- name: install docker
  become: true
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: install docker-compose
  become: true
  block:
    - ghcommand:
        name: docker/compose
    - file:
        src: /usr/local/bin/docker-compose
        dest: /usr/libexec/docker/cli-plugins/docker-compose
        state: link

- name: add permission
  become: true
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker

