# refs https://docs.docker.com/engine/install/ubuntu/
- name: install depencencies
  become: true
  apt:
    pkg:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release

- name: app repository
  become: true
  block:
    - apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/trusted.gpg.d/docker.gpg
        state: present
    - apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable"
        state: present

- name: install docker
  become: true
  apt:
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io

- name: add permission
  become: true
  user:
    name: "{{ ansible_user }}"
    append: yes
    groups: docker

# workaround for launch error
# https://qiita.com/tkc_tsuchiya/items/f7f4d502d8e2728f69c5
- name: use legacy iptables
  become: true
  alternatives:
    name: iptables
    path: /usr/sbin/iptables-legacy
