- hosts: localhost
  become: true
  tasks:
    - name: use japan apt mirror
      replace:
        path: /etc/apt/sources.list
        regexp: "http://archive.ubuntu.com/ubuntu"
        replace: "http://linux.yz.yamagata-u.ac.jp/ubuntu/"
        backup: yes
    - name: apt-get update/upgrade
      apt:
        update_cache: true
        upgrade: true
    - name: install tool packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - ansible
        - colordiff
        - direnv
        - docker.io
        - docker-compose
        - fd-find
        - fish
        - git
        - golang
        - imagemagick
        - jq
        - mariadb-client
        - neovim
        - peco
        - python3
        - python3-pip
        - ripgrep
        - sqlite
        - tig
        - tmux
        - tree
        - whois
    - name: install dev packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - libsqlite3-dev
    - name: chsh fish
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/fish

- hosts: localhost
  vars_files:
    - variables
  tasks:
    - include: dotfiles.yaml
    - include: anyenv.yaml
    - include: commands.yaml
