# 理由は全然わからないが、var_filesを使うには一旦var_filesなしのホストを実行しないと謎のエラーになる
- hosts: localhost
  tasks: []

- hosts: localhost
  vars_files:
    - variables
  tasks:
    - name: use japan apt mirror
      become: true
      replace:
        path: /etc/apt/sources.list
        regexp: "http://archive.ubuntu.com/ubuntu"
        replace: "https://linux.yz.yamagata-u.ac.jp/ubuntu"
        backup: yes
    - name: apt update/upgrade
      become: true
      apt:
        upgrade: 'yes'
        update_cache: yes
    - include: packages.yaml
    - include: wsl.yaml
    - include: dotfiles.yaml
    - include: anyenv.yaml
    - include: commands.yaml
    - include: docker-ce.yaml
    - include: golang.yaml
    - include: google-cloud-sdk.yaml
    - include: azure-cli.yaml
  handlers:
    - name: restart systemd-timesyncd
      become: true
      systemd:
        name: systemd-timesyncd.service
        state: restarted
        daemon_reload: yes
