- hosts: localhost
  user: medalhkr
  become: true
  tasks:
    - name: use japan apt mirror
      replace:
        path: /etc/apt/sources.list
        regexp: "http://archive.ubuntu.com/ubuntu"
        replace: "http://linux.yz.yamagata-u.ac.jp/ubuntu/"
        backup: yes
    - name: set fs max_user_watches
      sysctl:
        name: fs.inotify.max_user_watches
        value: 65535
        state: present
        reload: yes
    - name: apt add repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - ppa:fish-shell/release-3
        - ppa:longsleep/golang-backports
    - name: apt-get update/upgrade
      apt:
        update_cache: true
        upgrade: true
    - name: install packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - colordiff
        - direnv
        - docker.io
        - fish
        - git
        - golang-go
        - imagemagick
        - jq
        - neovim
        - peco
        - python3
        - python3-pip
        - sqlite
        - tig
        - tmux
        - tree
    - name: chsh fish
      user:
        name: medalhkr
        shell: /usr/bin/fish

- hosts: localhost
  user: medalhkr
  vars_files:
    - variables
  tasks:
    - include: dotfiles.yaml
    - include: anyenv.yaml
    - include: commands.yaml

- hosts: localhost
  user: medalhkr
  tasks:
    - name: Gather the apt package facts
      package_facts:
        manager: auto
    - name: Print the package facts to a file
      local_action: copy content={{ ansible_facts.packages | to_yaml }} dest=packages
