# 理由は全然わからないが、var_filesを使うには一旦var_filesなしのホストを実行しないと謎のエラーになる
- hosts: localhost
  tasks: []

- hosts: localhost
  vars_files:
    - variables
  tasks:
    - include_tasks:
        file: "{{ task_file }}"
      loop:
        - setup-apt.yaml
        - packages.yaml
        - wsl.yaml
        - dotfiles.yaml
        - anyenv.yaml
        - commands.yaml
        - docker-ce.yaml
        - golang.yaml
        - google-cloud-sdk.yaml
        - azure-cli.yaml
      loop_control:
        loop_var: task_file
  handlers:
    - name: restart systemd-timesyncd
      become: true
      systemd:
        name: systemd-timesyncd.service
        state: restarted
        daemon_reload: yes
