- hosts: all
  user: medalhkr
  tasks:
    - name: apt add repositories
      become: true
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - ppa:fish-shell/release-3
        - ppa:neovim-ppa/stable
    - name: apt-get update
      become: true
      apt:
        update_cache: true
    - name: install packages
      become: true
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - ansible
        - direnv
        - fish
        - git
        - golang
        - imagemagick
        - jq
        - neovim
        - nodejs
        - peco
        - python
        - python3
        - ruby
        - tig
        - tmux
        - tree

- hosts: all
  user: medalhkr
  tasks:
    - name: Gather the apt package facts
      package_facts:
        manager: auto
    - name: Print the package facts to a file
      local_action: copy content={{ ansible_facts.packages | to_yaml }} dest=packages.yaml
