- hosts: localhost
  become: true
  tasks:
    - name: use japan apt mirror
      replace:
        path: /etc/apt/sources.list
        regexp: "http://archive.ubuntu.com/ubuntu"
        replace: "http://linux.yz.yamagata-u.ac.jp/ubuntu/"
        backup: yes
    - name: apt-get update/upgrade
      apt:
        update_cache: yes
        upgrade: 'yes'
    - name: install tool packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - fd-find
        - golang
        - imagemagick
        - mariadb-client
        - python3
        - python3-pip
        - ripgrep
        - sqlite
        - tmux
        - tree
        - unzip
        - whois
        - zip
    - name: install dev packages
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - libmariadb-dev
        - libsqlite3-dev
    - name: chsh fish
      user:
        name: "{{ ansible_user }}"
        shell: /usr/bin/fish
    - name: setup directories
      file:
        path: '{{ item }}'
        state: directory
        owner: "{{ ansible_user }}"
      loop:
        - /opt/bin
        - /opt/bin/go

- hosts: localhost
  vars_files:
    - variables
  tasks:
    - include: winfiles.yaml
    - include: dotfiles.yaml
    - include: anyenv.yaml
    - include: commands.yaml
