- hosts: all
  user: medalhkr
  become: true
  tasks:
    - name: use japan apt mirror
      replace:
        path: /etc/apt/sources.list
        regexp: 'http://archive.ubuntu.com/ubuntu'
        replace: 'http://linux.yz.yamagata-u.ac.jp/ubuntu/'
        backup: yes
    - name: apt add repositories
      apt_repository:
        repo: "{{ item }}"
        state: present
      loop:
        - ppa:fish-shell/release-3
        - ppa:longsleep/golang-backports
    - name: apt add nodejs repository
      shell: |
        curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
        echo 'deb https://deb.nodesource.com/node_10.x bionic main' > /etc/apt/sources.list.d/nodesource.list
        echo 'deb-src https://deb.nodesource.com/node_10.x bionic main' >> /etc/apt/sources.list.d/nodesource.list
    - name: apt-get update
      apt:
        update_cache: true
    - name: install packages
      apt:
        name: "{{ item }}"
        state: latest
      loop:
        - colordiff
        - direnv
        - docker.io
        - fish
        - git
        - golang-go
        - imagemagick
        - jq
        - neovim
        - nodejs
        - peco
        - python3
        - python3-pip
        - ruby
        - sqlite
        - tig
        - tmux
        - tree

- hosts: all
  user: medalhkr
  vars_files:
    - variables
  tasks:
    - include: dotfiles.yaml
    - include: diff-highlight.yaml
    - include: go-commands.yaml
    - include: python-commands.yaml

- hosts: all
  user: medalhkr
  tasks:
    - name: Gather the apt package facts
      package_facts:
        manager: auto
    - name: Print the package facts to a file
      local_action: copy content={{ ansible_facts.packages | to_yaml }} dest=packages
