- name: setup gopath
  become: true
  block:
    - file:
        path: "/opt/go/gopath"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
    - lineinfile:
        path: /etc/profile.d/golang.sh
        regexp: "^export GOPATH="
        line: "export GOPATH=/opt/go/gopath"
        create: yes

- name: setup latest go release
  become: true
  block:
    - uri:
        url: https://go.dev/VERSION?m=text
        return_content: true
      register: version_raw
    - set_fact:
        version: "{{ version_raw.content.splitlines()[0] }}"

    - file:
        path: /opt/go/releases/{{ version }}
        state: directory

    - get_url:
        url: "https://go.dev/dl/{{ version }}.linux-amd64.tar.gz"
        dest: "/opt/go/releases/{{ version }}.linux-amd64.tar.gz"
    - name: install go
      unarchive:
        src: "/opt/go/releases/{{ version }}.linux-amd64.tar.gz"
        dest: "/opt/go/releases/{{ version }}"
        remote_src: true
        extra_opts: '--strip-components=1'

    - file:
        src: "/opt/go/releases/{{ version }}"
        dest: "/opt/go/current"
        state: link
    - lineinfile:
        path: /etc/profile.d/golang.sh
        regexp: "^export GOROOT="
        line: "export GOROOT=/opt/go/current"
        create: yes

