# refs https://github.com/golang/go/wiki/Ubuntu
- name: app repository
  become: true
  apt_repository:
    repo: "ppa:longsleep/golang-backports"
    state: present

- name: install golang
  become: true
  apt:
    name: golang-go
    state: present

- name: setup GOPATH directory
  become: true
  file:
    path: "/opt/go"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
