- name: use japan apt mirror
  become: true
  replace:
    path: /etc/apt/sources.list
    regexp: "http://archive.ubuntu.com/ubuntu"
    replace: "https://linux.yz.yamagata-u.ac.jp/ubuntu"
    backup: yes
- name: install tool packages
  become: true
  apt:
    state: latest
    update_cache: yes
    pkg:
      - apache2-utils
      - fd-find
      - imagemagick
      - mariadb-client
      - pwgen
      - redis-tools
      - ripgrep
      - sqlite
      - tree
      - unzip
      - whois
      - zip
- name: install dev packages
  become: true
  apt:
    state: latest
    pkg:
      - libmariadb-dev
      - libsqlite3-dev
- name: install aws-vault
  become: true
  apt:
    state: latest
    pkg:
      - pass
      - gnupg
- name: apt-get update/upgrade
  become: true
  apt:
    upgrade: 'yes'
