- name: install tool packages
  become: true
  apt:
    pkg:
      - apache2-utils
      - fd-find
      - imagemagick
      - mariadb-client
      - pwgen
      - redis-tools
      - ripgrep
      - sqlite
      - tree
      - unzip
      - whois
      - zip
- name: install dev packages
  become: true
  apt:
    pkg:
      - libmariadb-dev
      - libsqlite3-dev
- name: install aws-vault
  become: true
  apt:
    pkg:
      - pass
      - gnupg
