# python依存CLI群は標準パッケージだと何かとpython2/3やpipなどの兼ね合いでバグりがちなため
# python3のpipからインストールに統一しておく
- name: install python commands
  become: true
  pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  loop:
    - ansible
    - awscli
    - docker-compose
- name: install awscli session manager plugin
  become: true
  apt:
    deb: https://s3.amazonaws.com/session-manager-downloads/plugin/latest/ubuntu_64bit/session-manager-plugin.deb
