memodir = "~/.config/memo/_posts"
editor = "nvim"
column = 20
selectcmd = "peco"
grepcmd = "pt ${PATTERN} ${FILES}"
assetsdir = "."
pluginsdir = "~/.config/memo/plugins"
templatedirfile = ""
templatebodyfile = ""
