// See https://hyper.is#cfg for all currently supported options.

module.exports = {
  config: {
    updateChannel: 'stable',
    fontSize: 18,
    fontFamily: 'Cica, Menlo, "DejaVu Sans Mono", Consolas, "Lucida Console", monospace',
    fontWeight: 'normal',
    fontWeightBold: 'Bold',
    cursorColor: 'rgba(248,28,229,0.8)',
    cursorAccentColor: '#000',
    cursorShape: 'BLOCK',
    cursorBlink: false,
    foregroundColor: '#fff',
    backgroundColor: '#000',
    selectionColor: 'rgba(248,28,229,0.3)',
    borderColor: '#333',
    css: '',
    termCSS: '',
    showHamburgerMenu: '',
    showWindowControls: '',
    padding: '6px 6px',
    colors: {
      black: '#000000',
      red: '#d81e00',
      green: '#5ea702',
      yellow: '#cfae00',
      blue: '#427ab3',
      magenta: '#89658e',
      cyan: '#00a7aa',
      white: '#dbded8',
      lightBlack: '#686a66',
      lightRed: '#f54235',
      lightGreen: '#99e343',
      lightYellow: '#fdeb61',
      lightBlue: '#84b0d8',
      lightMagenta: '#bc94b7',
      lightCyan: '#37e6e8',
      lightWhite: '#f1f1f0',
    },
    shell: '',
    shellArgs: ['-c tmux;exit'],
    env: {},
    bell: 'SOUND',
    copyOnSelect: false,
    defaultSSHApp: true,
    modifierKeys: {
      altIsMeta: true,
    },
  },
  plugins: [],
  localPlugins: [],
  keymaps: {
  },
};
