set number
colorscheme molokai
set t_Co=256
syntax enable

if has('unix')
    set clipboard=unnamedplus
    let $PYTHONPATH='/usr/lib/python3.5/site-packages'
endif
if has('mac')
    set clipboard+=unnamed
    set backspace=indent,eol,start
    let $PYTHONPATH='/Users/medalhkr/Library/Python/3.5/lib/python/site-packages'
endif
set nocompatible
set expandtab
set nobackup
set noswapfile
set shiftwidth=4
set softtabstop=4
set tabstop=4
set autoindent
set smartindent
set textwidth=80
set nowrap
autocmd! BufNewFile,BufRead *.ino setlocal ft=arduino

set cursorline
highlight clear CursorLine

highlight Normal ctermbg=none
highlight LineNr ctermbg=none

let loaded_matchparen = 1
if exists('&colorcolumn')
    set colorcolumn=+1
endif
inoremap {<Enter> {<Enter>}<ESC><S-o>
set formatoptions=q

python from powerline.vim import setup as powerline_setup
python powerline_setup()
python del powerline_setup
set laststatus=2 " Always display the statusline in all windows
set showtabline=2 " Always display the tabline, even if there is only one tab
set noshowmode " Hide the default mode text (e.g. -- INSERT -- below the statusline)
