set number
colorscheme molokai
set t_Co=256
syntax enable

if has('unix')
    set clipboard=unnamedplus
endif
if has('mac')
    set clipboard+=unnamed
    set backspace=indent,eol,start
endif
set nocompatible
set expandtab
set nobackup
set noswapfile
set shiftwidth=4
set softtabstop=4
set tabstop=4
set autoindent
set smartindent
set textwidth=80
set nowrap
autocmd! BufNewFile,BufRead *.ino setlocal ft=arduino

set cursorline
highlight clear CursorLine

highlight Normal ctermbg=none
highlight LineNr ctermbg=none

let loaded_matchparen = 1
if exists('&colorcolumn')
    set colorcolumn=+1
endif
inoremap {<Enter> {<Enter>}<ESC><S-o>
set formatoptions=q
