#!/bin/bash

if [ $1 = "-usage" ]; then
    echo "memo edit with prefilter"
    exit 0
fi

selected=$(memo list | grep "$1")

if [ $(echo "$selected" | wc -l) -ne 1 ]; then
    selected=$(memo list | grep "$1" | peco)
fi

test -z "$selected" && exit 0

memo e $selected
