#!/bin/bash
test -z "$1" && echo "memo: pattern required" && exit 1

selected=$(memo g $1 | sed "s/\([^:]*:[^:]*\):\(.*\)/\1	| \2/g" | sed "s|.*/\([^:]*:\)|\1|g" | column -t -s "	" | peco)
test -z "$selected" && exit 0

memo e $(echo "$selected" | cut -d':' -f1)
