#!/bin/bash

if [ "$1" = "-usage" ]; then
    echo "list memo and edit one from the list"
    exit 0
fi

selected=$(memo list --format "{{.File}}:{{.Title}}" | column -t -s ":" | peco)
test -z "$selected" && exit 0

memo e $(echo "$selected" | cut -d':' -f1)
