#!/bin/bash

if [ "$1" = "-usage" ]; then
    echo "memo for tmp"
    exit 0
fi

readonly MEMODIR="${HOME}/.config/memo/_tmp"
readonly TODAY_FILE="$(date +%Y-%m-%d)-tmp.md"

case "$1" in
    "" | "n" | "new")
        env MEMODIR=$MEMODIR memo edit $TODAY_FILE
        ;;
    "l" | "line")
        # override "l" as "list"
        echo "$2" >> "${MEMODIR}/${TODAY_FILE}"
        ;;
    "tmp")
        echo "nest of memo tmp"
        exit 1
        ;;
    * )
        env MEMODIR=$MEMODIR memo $@
        ;;
esac
