#!/bin/sh

ICON_HOUSE="\$HOME"
#ICON_HOUSE=$(printf '\xF0\x9F\x8F\xA0')
ICON_GITHUB=$(printf '\xEf\x90\x88 ')

echo "${1:-$(pwd)}" | \
  sed "s|$HOME|$ICON_HOUSE|" | \
  sed "s|/opt/var/ghq/github.com|${ICON_GITHUB}|" | \
  sed "s|/opt/var/go/src/github.com|${ICON_GITHUB}|"
