#!/bin/sh

cd $1
if git rev-parse --is-inside-work-tree >/dev/null 2>&1 ; then
    env RBENV_VERSION=$(rbenv versions --bare | tail -n 1) rbenv exec ruby $(dirname $0)/__tmux_status_git.rb
# else if ssh
else
    __tmux_status_pwd
fi
