#!/bin/sh

cd $1
if git rev-parse --is-inside-work-tree >/dev/null 2>&1 ; then
    #printf '\xEf\x90\x88 '
    #echo -n ''
    echo "[$(basename $(git rev-parse --show-toplevel))]"
# else if ssh
else
    basename $(__tmux_status_pwd)
fi
