#!/bin/bash

asdf plugin update --all > /dev/null

node=$(asdf nodejs resolve lts --latest-available)
asdf install nodejs $node
asdf global nodejs $node

for c in "ruby" "golang" "terraform"; do
  # 数字だけに絞ることでjrubyなどの別種やrc版などを取り除く
  version=$(asdf list all $c | grep "^[0-9\.]*\$" | tail -n 1)
  asdf install $c $version
  asdf global $c $version
done
