#!/bin/bash

# usage: aws_set_token | source

set -eu

echo -n 'MFA: ' >&2; read token

raw=$(
  aws sts assume-role \
    --profile login_user \
    --role-arn $(aws configure get role_arn) \
    --role-session-name $(hostname) \
    --serial-number $(aws configure get mfa_serial) \
    --token-code $token
)

echo "set -x AWS_ACCESS_KEY_ID $(echo $raw | jq -r '.Credentials.AccessKeyId')"
echo "set -x AWS_SECRET_ACCESS_KEY $(echo $raw | jq -r '.Credentials.SecretAccessKey')"
echo "set -x AWS_SESSION_TOKEN $(echo $raw | jq -r '.Credentials.SessionToken')"
