#!/bin/bash

# usage: aws_set_token | source

role_arn=$(aws configure get role_arn)
raw=$(aws sts assume-role --role-arn $role_arn --role-session-name $(hostname))

echo "set -x AWS_ACCESS_KEY_ID $(echo $raw | jq -r '.Credentials.AccessKeyId')"
echo "set -x AWS_SECRET_ACCESS_KEY $(echo $raw | jq -r '.Credentials.SecretAccessKey')"
echo "set -x AWS_SESSION_TOKEN $(echo $raw | jq -r '.Credentials.SessionToken')"
