#!/usr/bin/env python3

import os
import sys
import configparser

c = configparser.ConfigParser()
c.read(os.path.expanduser('~/.aws/config'))
print(c['profile ' + sys.argv[1]]['role_arn'].split(':')[4])
