#!/bin/bash

ROOT=$HOME/repos

BAK=$ROOT.bak
mkdir -p $BAK

find $ROOT -maxdepth 3 -mindepth 3 -type d,l -printf '%P\n' | while read REPO; do
  echo "### "$(echo $REPO | sed "s|github\.com/||")
  cd $ROOT/$REPO

  git ls-files --others | \
    grep -v -e tmp -e uploads -e node_modules |
    while read FILE; do
      # ls-fliesなのでディレクトリが入ることはないが、symlinkが入ることはあるので、それは除外
      test -L $FILE && continue

      DEST=$BAK/$REPO/$FILE
      mkdir -p $(dirname $DEST)
      cp $FILE $DEST
    done
done

cd $HOME
tar czf repos.bak.tgz repos.bak
