#!/bin/bash

set -eu

# .terraform.d
#   場所を変更できるようにするための要求issueは多数あるが、解消されそうにない

cd $HOME

TARGET=(
 .azure
 .irb_history
 .python_history
 .degit
 .wget-hsts
 .serverless
 .serverlessrc
 .pylint.d
 .viminfo
 .npm
 .yarn
 .yarnrc
)
rm -rf ${TARGET[@]}
