#!/bin/bash

USER=$(git config --get user.name || echo $GIT_AUTHOR_NAME)

branch=$(gh pr list --json 'number,title,author,headRefName' \
  --jq ".[] | [.number, .author.login, .title, .headRefName] | @tsv" | \
  sed s/$USER/[me]/g | \
  peco --query '[me]' | cut -f 4)

test -z $branch && exit

git fetch --quiet origin $branch
git switch $branch
git branch --quiet $branch --set-upstream-to origin/$branch
