#!/bin/bash

USER=$(git config --get user.name)

branch=$(gh pr list --json 'number,title,author,headRefName' \
  --jq ".[] | [.number, .author.login, .title, .headRefName] | @csv" | \
  column -t -s',' | peco --query $USER | sed 's/.*"\([^"]*\)"$/\1/')

test -z $branch && exit

git fetch --quiet origin $branch
git switch $branch
git branch --quiet $branch --set-upstream-to origin/$branch
