#!/bin/sh

if git rev-parse --is-inside-work-tree >/dev/null 2>&1 ; then
    git status --branch --porcelain | $(dirname $0)/__status_git
else
    pwd | sed "s|$HOME|\$HOME|"
fi

echo "\n"

git status -s

echo ""

git log --oneline -3
