#!/bin/bash

ROOT=$HOME/repos

find $ROOT -maxdepth 3 -mindepth 3 -type d,l | while read LINE; do
  echo "### "$(echo $LINE | sed "s|$ROOT||")
  cd $LINE
  git status --branch --porcelain | __status_git
  echo ""
done
