#!/bin/bash

set -eu

cd $1
test ! -d .git && echo aaa && exit
REPOPATH=$PWD

git clone --depth 1 file://$REPOPATH ${REPOPATH}__
rsync -ac --delete --exclude .git ${REPOPATH}/ ${REPOPATH}__
rm -rf $REPOPATH
mv ${REPOPATH}__ $REPOPATH
