#!/usr/bin/env perl

open (FILE, "$ENV{HOME}/.ssh/config");
my $print = 0;
while (<FILE>) {
    if ($_ =~ /^Host .*$ARGV[0]/) {
        print "\n$.: ";
        $print = 1;
    }
    $print = 0 if $_ eq "\n";
    print $_ if $print;
}
