[core]
  editor = "nvim"
  selectcmd = "peco"
  tomlfile = "/home/medalhkr/.config/gist/config.toml"
  user = "cumet04"

[gist]
  token = "$GITHUB_TOKEN"
  base_url = "https://gist.github.com"
  dir = "/home/medalhkr/.cache/gist"
  file_ext = ".patch"
  use_cache = true
  cache_ttl = 86400000000000
  runnable_ext = ["sh", "rb", "py", "pl", "php"]

[flag]
  open_url = true
  blog_mode = true
  starred = false

[screen]
  columns = ["{{.ShortID}}", "{{.PrivateMark}} {{.Filename}}", "{{.Description}}"]
